from typing import Protocol, List, runtime_checkable


@runtime_checkable
class IRecentFoldersService(Protocol):
    def load_recent_folders(self) -> List[str]: ...

    def save_recent_folders(self, folders: List[str]) -> None: ...

    def clear_recent_folders(self) -> None: ...

    def add_recent_folder(self, folder_path: str) -> bool: ...

    def get_folder_display_name(self, folder_path: str) -> str: ...
