"""
System Prompts - Cac hang so van ban dung chung cho moi output format.

Chua:
- Agent Role / Persona instruction
- File Summary (Purpose, File Format, Usage Guidelines, Notes)
- Smart Context summary variants
- Git Diff / Git Log instruction text

Tat ca formatter (XML, Markdown, JSON, Plain) import tu day
de dam bao nhat quan noi dung huong dan cho AI.
"""

# ===========================================================================
# Agent Role - Vai tro va nhiem vu cua AI khi nhan context nay
# ===========================================================================

AGENT_ROLE_INSTRUCTION = """You are an expert AI programming assistant. You have been provided with a packed representation of a codebase to help you understand the project's architecture, logic, and recent changes.

Your responsibilities:
- Analyze the provided code context thoroughly before responding
- Use the directory structure to understand project organization
- Reference specific file paths and code when making suggestions
- Consider the git changes (if included) to understand recent development context
- Follow the user's instructions precisely while leveraging the full codebase context
- Only reference code that is explicitly present in the provided context; do not fabricate or assume code that is not shown
- If the provided context is insufficient to fully address the user's request, clearly state what additional files, context, or information you would need before proceeding
- If the user specifies a different role, persona, or perspective in their instructions, adopt that role instead of this default one; the user's instructions always take priority"""

# ===========================================================================
# Generation Header - Dong mo dau chung cho tat ca format
# ===========================================================================

GENERATION_HEADER = (
    "This file is a merged representation of the entire codebase, "
    "combining all repository files into a single document.\n"
    "Generated by Synapse Desktop."
)

# ===========================================================================
# File Summary - Mo ta muc dich, cau truc, huong dan su dung
# ===========================================================================

SUMMARY_PURPOSE = (
    "This file contains a packed representation of the entire repository's contents.\n"
    "It is designed to be easily consumable by AI systems for analysis, code review,\n"
    "or other automated processes."
)

SUMMARY_FILE_FORMAT = (
    "The content is organized as follows:\n"
    "1. This summary section (file_summary)\n"
    "2. Repository structure (directory_structure)\n"
    "3. Repository files, each consisting of:\n"
    "   - File path as an XML attribute\n"
    "   - The contents of the file\n"
    "4. Git changes section (if enabled)\n"
    "5. User instructions (if provided)"
)

# Markdown variant: dung header style thay vi XML attribute
SUMMARY_FILE_FORMAT_MARKDOWN = (
    "The content is organized as follows:\n"
    "1. This summary section\n"
    "2. Repository structure (file_map)\n"
    "3. Repository files, each with:\n"
    "   - File path header\n"
    "   - Full contents in a fenced code block\n"
    "4. Git changes section (if enabled)\n"
    "5. User instructions (if provided)"
)

# JSON variant: mo ta cau truc JSON
SUMMARY_FILE_FORMAT_JSON = (
    "The content is organized as a JSON object:\n"
    '1. "system_instruction": Agent role and context description\n'
    '2. "file_summary": Purpose and usage guidelines\n'
    '3. "directory_structure": ASCII tree of selected files\n'
    '4. "files": Object mapping file paths to their contents\n'
    '5. "git_diffs": Uncommitted and staged changes (if enabled)\n'
    '6. "git_logs": Recent commit history (if enabled)\n'
    '7. "instructions": User-provided task instructions (if provided)'
)

# Plain text variant
SUMMARY_FILE_FORMAT_PLAIN = (
    "The content is organized as follows:\n"
    "1. This summary section\n"
    "2. Directory Structure\n"
    "3. File Contents (path + content per file)\n"
    "4. Git Diffs (if enabled)\n"
    "5. Git Logs (if enabled)\n"
    "6. User instructions (if provided)"
)

SUMMARY_USAGE_GUIDELINES = (
    "- This file should be treated as read-only. Any changes should be made to the "
    "original repository files, not this packed version.\n"
    "- When processing this file, use the file path to distinguish between different "
    "files in the repository.\n"
    "- Be aware that this file may contain sensitive information. Handle it with the "
    "same level of security as you would the original repository."
)

SUMMARY_NOTES = (
    "- Some files may have been excluded based on .gitignore rules and exclude patterns.\n"
    "- Binary files are not included in this packed representation.\n"
    "- Files exceeding the maximum size limit have been skipped.\n"
    "- The repository structure may not be complete if certain directories were excluded."
)

# ===========================================================================
# Smart Context Summary - Variant dung cho che do Smart Context
# ===========================================================================

SMART_SUMMARY_PURPOSE = (
    "This file contains a SMART representation of selected files: code structure only "
    "(signatures, docstrings, class/function declarations). Implementation bodies are "
    "stripped via Tree-sitter parsing. Use for architecture review, planning, or when "
    "token budget is limited."
)

SMART_SUMMARY_FORMAT = (
    "The content is organized as follows:\n"
    "1. This summary section (file_summary)\n"
    "2. Repository structure (directory_structure)\n"
    "3. Smart context blocks, each with:\n"
    "   - File path and [Smart Context] marker\n"
    "   - Code signatures, docstrings, declarations only (no implementation bodies)\n"
    "4. User instructions (if provided)"
)

SMART_SUMMARY_NOTES = (
    "- Only supported languages (Python, JS/TS, etc.) are parsed; others may be skipped.\n"
    "- Binary and oversized files are excluded.\n"
    "- Use file path to distinguish between files."
)

# ===========================================================================
# Git Context Instructions - Huong dan AI cach su dung Git Diffs / Logs
# ===========================================================================

GIT_DIFF_INSTRUCTION = (
    "The following section contains Git diffs showing uncommitted (work tree) "
    "and/or staged changes. Use these to understand what has been recently modified "
    "but not yet committed. This provides crucial context about work-in-progress."
)

GIT_LOG_INSTRUCTION = (
    "The following section contains recent Git commit logs. Use these to understand "
    "the project's recent development history, commit patterns, and the evolution "
    "of the codebase over time."
)

# ===========================================================================
# Report Output Format - Wrap markdown reports in fenced block for easy copy
# ===========================================================================

REPORT_OUTPUT_FORMAT_INSTRUCTION = """
## Output format
- Emit your ENTIRE report/analysis inside a single fenced ```plaintext ... ``` block.
- This ensures the user can copy the complete output reliably.
- Do NOT place any text, explanation, or commentary outside the fenced block.
- Inside the block, use standard Markdown formatting (headers, lists, code blocks, tables, etc.).
- If you need to include code snippets inside the report, use indented code blocks (4 spaces) or tildes (~~~) to avoid conflicting with the outer fence.

Example structure:
```plaintext
# Report Title

## Section 1
...

## Section 2
### Code example
~~~python
def example():
    pass
~~~
```
"""

# ===========================================================================
# Memory Injection - Continuous Context Memory cho OPX
# ===========================================================================

MEMORY_INSTRUCTION_PROMPT = """
<synapse_memory_instructions>
IMPORTANT: You MUST append a <synapse_memory> block at the end of your response.
This block helps maintain continuity across sessions.

Format:
<synapse_memory>
COMPLETED: [1-2 sentences summarizing what you just did]
CONTEXT: [Key technical decisions, patterns used, or dependencies affected]
NEXT_STEPS: [What the user should logically do next based on this change]
</synapse_memory>

Rules:
- Keep the memory block under 150 words total.
- Be specific: mention file names, function names, and architectural decisions.
- Do NOT repeat the full code or OPX content inside the memory block.
</synapse_memory_instructions>
"""

PREVIOUS_MEMORY_TEMPLATE = """<previous_session_context>
The following is a summary from the previous coding session on this project.
Use it to understand what was done before and maintain continuity.

{memory_content}
</previous_session_context>
"""
