"""
XML Formatter - Render file contents thanh Repomix XML format.

Bao gom:
- format_files_xml(): File contents dang XML
- generate_file_summary_xml(): AI-friendly file_summary section
- generate_smart_summary_xml(): Smart Context file_summary section

Extracted tu: generate_file_contents_xml(), generate_file_summary_xml(),
             generate_smart_summary_xml() trong core/prompt_generator.py
"""

import html

from core.prompting.types import FileEntry


# === XML String Templates ===
# Giu nguyen 100% tu prompt_generator.py de dam bao output khong thay doi

GENERATION_HEADER = """This file is a merged representation of the entire codebase, combining all repository files into a single document.
Generated by Synapse Desktop."""

SUMMARY_PURPOSE = """This file contains a packed representation of the entire repository's contents.
It is designed to be easily consumable by AI systems for analysis, code review,
or other automated processes."""

SUMMARY_FILE_FORMAT = """The content is organized as follows:
1. This summary section (file_summary)
2. Repository structure (directory_structure) 
3. Repository files, each consisting of:
   - File path as an XML attribute
   - The contents of the file
4. Git changes section (if enabled)
5. User instructions (if provided)"""

SUMMARY_USAGE_GUIDELINES = """- This file should be treated as read-only. Any changes should be made to the original repository files, not this packed version.
- When processing this file, use the file path to distinguish between different files in the repository.
- Be aware that this file may contain sensitive information. Handle it with the same level of security as you would the original repository."""

SUMMARY_NOTES = """- Some files may have been excluded based on .gitignore rules and exclude patterns.
- Binary files are not included in this packed representation.
- Files exceeding the maximum size limit have been skipped.
- The repository structure may not be complete if certain directories were excluded."""

# Smart Context
SMART_SUMMARY_PURPOSE = """This file contains a SMART representation of selected files: code structure only (signatures, docstrings, class/function declarations). Implementation bodies are stripped via Tree-sitter parsing. Use for architecture review, planning, or when token budget is limited."""

SMART_SUMMARY_FORMAT = """The content is organized as follows:
1. This summary section (file_summary)
2. Repository structure (directory_structure)
3. Smart context blocks, each with:
   - File path and [Smart Context] marker
   - Code signatures, docstrings, declarations only (no implementation bodies)
4. User instructions (if provided)"""

SMART_SUMMARY_NOTES = """- Only supported languages (Python, JS/TS, etc.) are parsed; others may be skipped.
- Binary and oversized files are excluded.
- Use file path to distinguish between files."""


def format_files_xml(entries: list[FileEntry]) -> str:
    """
    Render List[FileEntry] thanh Repomix XML format.

    Output format:
        <files>
          <file path="src/main.py">
            content (HTML-escaped)
          </file>
        </files>

    Args:
        entries: List file entries da doc tu file_collector

    Returns:
        File contents string voi XML structure
    """
    file_elements: list[str] = []

    for entry in entries:
        escaped_path = html.escape(entry.display_path)

        if entry.error:
            file_elements.append(
                f'<file path="{escaped_path}" skipped="true">{entry.error}</file>'
            )
        elif entry.content is not None:
            escaped_content = html.escape(entry.content)
            file_elements.append(
                f'<file path="{escaped_path}">\n{escaped_content}\n</file>'
            )

    if not file_elements:
        return "<files></files>"

    return "<files>\n" + "\n".join(file_elements) + "\n</files>"


def generate_file_summary_xml() -> str:
    """
    Tao section file_summary theo chuan Repomix AI-Friendly format.

    Section nay giup LLM hieu:
    - Muc dich cua file context
    - Cau truc du lieu ben trong
    - Cach su dung dung cach
    - Cac luu y quan trong

    Returns:
        XML string chua file_summary section
    """
    return f"""<file_summary>
{GENERATION_HEADER}

<purpose>
{SUMMARY_PURPOSE}
</purpose>

<file_format>
{SUMMARY_FILE_FORMAT}
</file_format>

<usage_guidelines>
{SUMMARY_USAGE_GUIDELINES}
</usage_guidelines>

<notes>
{SUMMARY_NOTES}
</notes>
</file_summary>
"""


def generate_smart_summary_xml() -> str:
    """
    Tao file_summary cho Smart Context mode.

    Mo ta rang day la code structure (signatures, docstrings) chu khong phai full content.

    Returns:
        XML string chua file_summary section cho Smart Context
    """
    return f"""<file_summary>
{GENERATION_HEADER}

<purpose>
{SMART_SUMMARY_PURPOSE}
</purpose>

<file_format>
{SMART_SUMMARY_FORMAT}
</file_format>

<usage_guidelines>
{SUMMARY_USAGE_GUIDELINES}
</usage_guidelines>

<notes>
{SMART_SUMMARY_NOTES}
</notes>
</file_summary>
"""
