"""
System Prompts - Cac hang so van ban dung chung cho moi output format.

Chua:
- Agent Role / Persona instruction
- File Summary (Purpose, File Format, Usage Guidelines, Notes)
- Smart Context summary variants
- Git Diff / Git Log instruction text

Tat ca formatter (XML, Markdown, JSON, Plain) import tu day
de dam bao nhat quan noi dung huong dan cho AI.
"""

# ===========================================================================
# Agent Role - Vai tro va nhiem vu cua AI khi nhan context nay
# ===========================================================================

AGENT_ROLE_INSTRUCTION = """You are an expert programming assistant partnering with a developer. You've been given a packed representation of their codebase to help understand the project's architecture, logic, and recent changes.

How to work with this context:
- Analyze the provided code thoroughly before responding
- Use the directory structure to understand project organization
- Reference specific file paths and code when making suggestions
- Consider git changes (if included) to understand recent development context
- Follow the developer's instructions precisely while leveraging the full codebase context
- If a user_instructions block (or an "Instructions" section) appears later in this document, treat it as the highest-priority task directive and follow it first
- Only reference code explicitly present in the provided context; don't fabricate or assume code that isn't shown
- If the context is insufficient, clearly state what additional files or information you'd need before proceeding
- If the developer specifies a different role or perspective in their instructions, adopt that role; their instructions always take priority

When viewing Smart Context (signatures/declarations only):
- You can describe what functions/classes exist and their signatures
- You can't describe implementation details or internal logic

When git diffs are included:
- Distinguish between current code (files section) vs changes (diffs section)
- Use temporal language: "Before this change..." vs "After this change..." vs "Currently in the codebase..."
"""

# ===========================================================================
# Generation Header - Dong mo dau chung cho tat ca format
# ===========================================================================

GENERATION_HEADER = (
    "This file is a merged representation of the entire codebase, "
    "combining all repository files into a single document.\n"
    "Generated by Synapse Desktop."
)

# ===========================================================================
# File Summary - Mo ta muc dich, cau truc, huong dan su dung
# ===========================================================================

SUMMARY_PURPOSE = (
    "This file contains a packed representation of the entire repository's contents.\n"
    "It is designed to be easily consumable by AI systems for analysis, code review,\n"
    "or other automated processes."
)

SUMMARY_FILE_FORMAT = (
    "The content is organized as follows:\n"
    "1. This summary section (file_summary)\n"
    "2. Repository structure (directory_structure)\n"
    "3. Repository files, each consisting of:\n"
    "   - File path as an XML attribute\n"
    "   - The contents of the file\n"
    "4. Git changes section (if enabled)\n"
    "5. User instructions (if provided)"
)

# Markdown variant: dung header style thay vi XML attribute
SUMMARY_FILE_FORMAT_MARKDOWN = (
    "The content is organized as follows:\n"
    "1. This summary section\n"
    "2. Repository structure (file_map)\n"
    "3. Repository files, each with:\n"
    "   - File path header\n"
    "   - Full contents in a fenced code block\n"
    "4. Git changes section (if enabled)\n"
    "5. User instructions (if provided)"
)

# JSON variant: mo ta cau truc JSON
SUMMARY_FILE_FORMAT_JSON = (
    "The content is organized as a JSON object:\n"
    '1. "system_instruction": Agent role and context description\n'
    '2. "file_summary": Purpose and usage guidelines\n'
    '3. "directory_structure": ASCII tree of selected files\n'
    '4. "files": Object mapping file paths to their contents\n'
    '5. "git_diffs": Uncommitted and staged changes (if enabled)\n'
    '6. "git_logs": Recent commit history (if enabled)\n'
    '7. "instructions": User-provided task instructions (if provided)'
)

# Plain text variant
SUMMARY_FILE_FORMAT_PLAIN = (
    "The content is organized as follows:\n"
    "1. This summary section\n"
    "2. Directory Structure\n"
    "3. File Contents (path + content per file)\n"
    "4. Git Diffs (if enabled)\n"
    "5. Git Logs (if enabled)\n"
    "6. User instructions (if provided)"
)

SUMMARY_USAGE_GUIDELINES = (
    "- This file should be treated as read-only. Any changes should be made to the "
    "original repository files, not this packed version.\n"
    "- When processing this file, use the file path to distinguish between different "
    "files in the repository.\n"
    "- Be aware that this file may contain sensitive information. Handle it with the "
    "same level of security as you would the original repository."
)

SUMMARY_NOTES = (
    "- Some files may have been excluded based on .gitignore rules and exclude patterns.\n"
    "- Binary files are not included in this packed representation.\n"
    "- Files exceeding the maximum size limit have been skipped.\n"
    "- The repository structure may not be complete if certain directories were excluded."
)

# ===========================================================================
# Smart Context Summary - Variant dung cho che do Smart Context
# ===========================================================================

SMART_SUMMARY_PURPOSE = (
    "This file contains a SMART representation of selected files: code structure only "
    "(signatures, docstrings, class/function declarations). Implementation bodies are "
    "stripped via Tree-sitter parsing. Use for architecture review, planning, or when "
    "token budget is limited."
)

SMART_SUMMARY_FORMAT = (
    "The content is organized as follows:\n"
    "1. This summary section (file_summary)\n"
    "2. Repository structure (directory_structure)\n"
    "3. Smart context blocks, each with:\n"
    "   - File path and [Smart Context] marker\n"
    "   - Code signatures, docstrings, declarations only (no implementation bodies)\n"
    "4. User instructions (if provided)"
)

SMART_SUMMARY_NOTES = (
    "- Only supported languages (Python, JS/TS, etc.) are parsed; others may be skipped.\n"
    "- Binary and oversized files are excluded.\n"
    "- Use file path to distinguish between files."
)

# ===========================================================================
# Git Context Instructions - Huong dan AI cach su dung Git Diffs / Logs
# ===========================================================================

GIT_DIFF_INSTRUCTION = (
    "The following section contains Git diffs showing uncommitted (work tree) "
    "and/or staged changes. Use these to understand what has been recently modified "
    "but not yet committed. This provides crucial context about work-in-progress."
)

GIT_LOG_INSTRUCTION = (
    "The following section contains recent Git commit logs. Use these to understand "
    "the project's recent development history, commit patterns, and the evolution "
    "of the codebase over time."
)
