"""
Global stylesheet helpers for Synapse Desktop.

The main QSS is generated by core/theme_qss.py.
This file provides utility functions for applying cursor/tooltip
and a thin convenience wrapper that merges theme_qss output.
"""

from PySide6.QtCore import Qt
from PySide6.QtWidgets import QPushButton, QWidget

from core.theme_qss import generate_app_stylesheet


def apply_cursor_pointer(widget: QWidget) -> None:
    """Apply pointer cursor to clickable widget."""
    widget.setCursor(Qt.CursorShape.PointingHandCursor)


def setup_button(button: QPushButton, tooltip: str = "") -> None:
    """Setup button with cursor pointer and optional tooltip."""
    apply_cursor_pointer(button)
    if tooltip:
        button.setToolTip(tooltip)


def get_global_stylesheet() -> str:
    """
    Return the complete application stylesheet.

    Delegates to generate_app_stylesheet() so there is exactly ONE
    source of truth for the global QSS.
    """
    return generate_app_stylesheet()
