"""
Handoff Formatter - Format output prompt cho agent workflow tools.

Tạo structured prompt bao gồm:
- Task description + scope explanation
- File map (cấu trúc cây thư mục các files được chọn)
- File contents (đã optimize bởi TokenBudgetManager)
- Relationship explanation (giải thích mối quan hệ giữa các files)
- Action instructions (hướng dẫn cụ thể cho AI agent)
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List
import html

from domain.prompt.formatters.system_prompts import AGENT_ROLE_INSTRUCTION
from domain.codemap.dependency_resolver import DependencyResolver


@dataclass
class HandoffContext:
    """
    Toàn bộ context cần thiết để format handoff prompt.

    Attributes:
        task_description: Mô tả task từ user
        file_contents: Map relative_path -> content (đã optimize)
        file_map: ASCII tree của các files
        relationships: Giải thích mối quan hệ giữa files
        action_instructions: Hướng dẫn cụ thể cho AI
        metadata: Thông tin bổ sung (token count, files sliced, etc.)
    """

    task_description: str = ""
    file_contents: Dict[str, str] = field(default_factory=dict)
    file_map: str = ""
    relationships: str = ""
    action_instructions: str = ""
    metadata: Dict[str, object] = field(default_factory=dict)
    extra_sections: Dict[str, str] = field(default_factory=dict)


def format_handoff_xml(context: HandoffContext) -> str:
    """
    Render HandoffContext thành XML prompt.

    Tái sử dụng structure từ core.prompting.formatters.xml
    để nhất quán với output format hiện tại của Synapse.

    Args:
        context: HandoffContext chứa toàn bộ dữ liệu

    Returns:
        XML string hoàn chỉnh, sẵn sàng paste cho AI agent
    """
    sections = []

    # Header
    sections.append("<synapse_context>")
    sections.append("<file_summary>")
    sections.append("Generated by Synapse Desktop - Agent Workflow Tool")
    sections.append("")
    sections.append("<agent_role>")
    sections.append(AGENT_ROLE_INSTRUCTION)
    sections.append("</agent_role>")
    sections.append("")
    sections.append("<task>")
    sections.append(html.escape(context.task_description))
    sections.append("</task>")
    sections.append("</file_summary>")
    sections.append("")

    # File map
    if context.file_map:
        sections.append("<file_map>")
        sections.append(html.escape(context.file_map))
        sections.append("</file_map>")
        sections.append("")

    # Relationships
    if context.relationships:
        sections.append("<relationships>")
        sections.append(html.escape(context.relationships))
        sections.append("</relationships>")
        sections.append("")

    # Extra sections (test_analysis, review_checklist, etc.)
    # Noi dung da duoc format san (XML) nen khong can escape
    for section_name, section_content in context.extra_sections.items():
        sections.append(f"<{section_name}>")
        sections.append(section_content)
        sections.append(f"</{section_name}>")
        sections.append("")

    # Files
    sections.append("<files>")
    for file_path, content in context.file_contents.items():
        if content:  # Skip None values
            escaped_path = html.escape(file_path)
            escaped_content = html.escape(content)
            sections.append(f'<file path="{escaped_path}">')
            sections.append(escaped_content)
            sections.append("</file>")
    sections.append("</files>")
    sections.append("")

    # Action instructions
    if context.action_instructions:
        sections.append("<instructions>")
        sections.append(html.escape(context.action_instructions))
        sections.append("</instructions>")
        sections.append("")

    # Metadata
    if context.metadata:
        sections.append("<metadata>")
        for key, value in context.metadata.items():
            sections.append(f"  {key}: {value}")
        sections.append("</metadata>")
        sections.append("")

    sections.append("</synapse_context>")

    return "\n".join(sections)


def format_relationships_section(
    workspace_path: Path,
    file_paths: List[str],
) -> str:
    """
    Tạo section mô tả mối quan hệ giữa các files.

    Dùng DependencyResolver để lấy dependency graph,
    sau đó render thành dạng dễ đọc.

    Args:
        workspace_path: Workspace root
        file_paths: Danh sách files cần phân tích

    Returns:
        Text mô tả relationships
    """
    resolver = DependencyResolver(workspace_path)
    resolver.build_file_index_from_disk(workspace_path)

    relationships = []
    relationships.append("File Dependencies:")
    relationships.append("")

    for rel_path in file_paths:
        file_path = (workspace_path / rel_path).resolve()
        if not file_path.exists():
            continue

        try:
            related = resolver.get_related_files(file_path, max_depth=1)
            if related:
                relationships.append(f"• {rel_path}")
                for dep_path in sorted(related):
                    try:
                        dep_rel = dep_path.relative_to(workspace_path).as_posix()
                        relationships.append(f"  → imports {dep_rel}")
                    except ValueError:
                        pass
        except Exception:
            pass

    if len(relationships) <= 2:
        return "No significant dependencies detected."

    return "\n".join(relationships)
