"""
Git Utilities - Handle git operations (diff, log, status)
"""

import shutil
import subprocess
import sys
import re
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional, Any, Protocol
import logging

# Single source of truth cho path display - thay the ban sao inline cu
# Truoc day inline de tranh circular import, gio an toan vi path_utils
# khong import git_utils hay prompt_generator
from shared.utils.path_utils import path_for_display


# Diff Only - file_summary mo ta context la git changes
DIFF_SUMMARY_HEADER = """This file contains git changes (diff) from the repository.
Generated by Synapse Desktop."""

DIFF_SUMMARY_PURPOSE = """This file contains a DIFF representation: uncommitted changes (staged + unstaged) and optionally recent commits. Use for code review, PR descriptions, or when you need AI to understand what changed."""

DIFF_SUMMARY_FORMAT = """The content is organized as follows:
1. This summary section (file_summary)
2. Diff context (files changed, line stats)
3. Project structure of changed files (if enabled)
4. Git diff content (unified diff format)
5. Full content of changed files (if enabled)
6. Full content of related files by import depth (if enabled)
7. User instructions (if provided)"""

DIFF_SUMMARY_NOTES = """- Paths are workspace-relative when use_relative_paths is enabled.
- Binary files may be excluded from changed_files_content."""


def _generate_diff_summary_xml() -> str:
    """Tao file_summary cho Copy Diff Only. Nhat quan voi Copy Context/Smart."""
    return f"""<file_summary>
{DIFF_SUMMARY_HEADER}

<purpose>
{DIFF_SUMMARY_PURPOSE}
</purpose>

<file_format>
{DIFF_SUMMARY_FORMAT}
</file_format>

<usage_guidelines>
- Use file path to distinguish between files.
- Apply changes to the original repository files, not this packed version.
</usage_guidelines>

<notes>
{DIFF_SUMMARY_NOTES}
</notes>
</file_summary>
"""


def _generate_diff_summary_plain() -> str:
    """Tạo file summary dạng plain text cho Copy Diff Only."""
    return f"""{"=" * 48}
FILE SUMMARY
{"=" * 48}
{DIFF_SUMMARY_HEADER}

Purpose:
{DIFF_SUMMARY_PURPOSE}

File Format:
{DIFF_SUMMARY_FORMAT}

Usage Guidelines:
- Use file path to distinguish between files.
- Apply changes to the original repository files, not this packed version.

Notes:
{DIFF_SUMMARY_NOTES}
"""


# Configure logger
logger = logging.getLogger(__name__)


def _new_str_list() -> list[str]:
    """Factory typed list[str] cho dataclass fields."""
    return []


def _new_git_commit_list() -> list["GitCommit"]:
    """Factory typed list[GitCommit] cho dataclass fields."""
    return []


class _OutputFormatLike(Protocol):
    value: str


_DIFF_GIT_HEADER_RE = re.compile(
    r'^diff --git (?:"a/(.*?)"|a/(\S+)) (?:"b/(.*?)"|b/(\S+))$'
)


@dataclass
class GitDiffResult:
    work_tree_diff: str = ""
    staged_diff: str = ""


@dataclass
class GitCommit:
    hash: str
    date: str
    message: str
    files: list[str] = field(default_factory=_new_str_list)


@dataclass
class GitLogResult:
    commits: list[GitCommit] = field(default_factory=_new_git_commit_list)
    log_content: str = ""
    commit_count: int = 0
    error: Optional[str] = None


@dataclass
class DiffOnlyResult:
    """Kết quả cho Copy Diff Only feature"""

    diff_content: str
    files_changed: int
    insertions: int
    deletions: int
    commits_included: int
    changed_files: list[str] = field(
        default_factory=_new_str_list
    )  # List of changed file paths
    error: Optional[str] = None


def is_git_installed() -> bool:
    """Check if git is installed and available in PATH."""
    return shutil.which("git") is not None


def is_git_repo(root_path: Path) -> bool:
    """
    Check if path is inside a git repository.
    Uses 'git rev-parse --is-inside-work-tree' for reliable check.
    """
    if not is_git_installed():
        return False

    try:
        result = subprocess.run(
            ["git", "-C", str(root_path), "rev-parse", "--is-inside-work-tree"],
            capture_output=True,
            text=True,
            check=False,
        )
        return result.returncode == 0 and result.stdout.strip() == "true"
    except Exception:
        return False


def get_git_diffs(
    root_path: Path, base_ref: Optional[str] = None
) -> Optional[GitDiffResult]:
    """
    Get git diff for working tree and staged changes.
    Equivalent to Repomix getGitDiffs.

    Args:
        root_path: Git repository root
        base_ref: Optional git ref to diff against (e.g., "main", "HEAD~1")
                 If None, diffs working tree and staged changes.

    Returns:
        GitDiffResult with work_tree_diff and staged_diff
    """
    if not is_git_repo(root_path):
        return None

    try:
        if base_ref:
            if base_ref.startswith("-"):
                logger.warning("Rejected suspicious base_ref: %s", base_ref)
                return None
            # Diff against specific ref
            diff_cmd = subprocess.run(
                ["git", "-C", str(root_path), "diff", "--no-color", base_ref, "--"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            return GitDiffResult(work_tree_diff=diff_cmd.stdout or "", staged_diff="")
        else:
            # Working tree diff (unstaged)
            # --no-color is important to avoid ANSI codes in output
            work_tree = subprocess.run(
                ["git", "-C", str(root_path), "diff", "--no-color"],
                capture_output=True,
                text=True,
                timeout=10,
            )

            # Staged diff
            staged = subprocess.run(
                ["git", "-C", str(root_path), "diff", "--staged", "--no-color"],
                capture_output=True,
                text=True,
                timeout=10,
            )

            return GitDiffResult(
                work_tree_diff=work_tree.stdout or "", staged_diff=staged.stdout or ""
            )
    except subprocess.TimeoutExpired:
        logger.warning("Git diff timed out")
        return None
    except Exception as e:
        logger.error(f"Failed to get git diffs: {e}")
        return None


def get_git_logs(root_path: Path, max_commits: int = 10) -> Optional[GitLogResult]:
    """
    Get recent git log with changed files.
    Equivalent to Repomix getGitLogs, but properly parsing output.
    """
    if not is_git_repo(root_path):
        return None

    # Format: %x00 (separator) + %h (hash) | %ad (date) | %s (subject)
    # Using %x00 in format string lets git output NULL bytes
    sep = "\x00"
    fmt = "%x00%h|%ad|%s"

    try:
        # git log command
        cmd = [
            "git",
            "-C",
            str(root_path),
            "log",
            f"--pretty=format:{fmt}",
            "--date=iso",
            "--name-only",
            "-n",
            str(max_commits),
        ]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=10,
            encoding="utf-8",
            errors="replace",
        )

        if result.returncode != 0:
            return None

        raw_output = result.stdout
        commits = _parse_git_log(raw_output, sep)

        # Windows clipboard/app destination co the truncate text khi gap NULL char (\x00).
        # Chi sanitize log_content tren Windows de tranh anh huong behavior tren Linux/macOS.
        display_output = raw_output
        if (
            display_output
            and "\x00" in display_output
            and sys.platform.startswith("win")
        ):
            display_output = display_output.replace("\x00", "\n")

        return GitLogResult(
            commits=commits,
            log_content=display_output,  # Raw content might be useful for debugging
        )

    except Exception as e:
        logger.error(f"Failed to get git logs: {e}")
        return None


def _parse_git_log(raw_output: str, separator: str) -> list[GitCommit]:
    """
    Parse raw git log output into structured GitCommit objects.
    Logic ported from Repomix gitLogHandle.ts parseGitLog
    """
    if not raw_output.strip():
        return []

    commits: list[GitCommit] = []

    # Split by NULL separator -> list of commit blocks
    # Filter empty strings (first element might be empty due to leading separator)
    entries = [e for e in raw_output.split(separator) if e]

    for entry in entries:
        lines = [line.strip() for line in entry.splitlines() if line.strip()]
        if not lines:
            continue

        # First line contains: hash|date|subject
        header = lines[0]
        parts = header.split("|", 2)

        if len(parts) < 3:
            continue

        commit_hash, date, message = parts[0], parts[1], parts[2]

        # Remaining lines are file paths
        files = lines[1:]

        commits.append(
            GitCommit(hash=commit_hash, date=date, message=message, files=files)
        )

    return commits


def get_diff_only(
    workspace_path: Path,
    num_commits: int = 1,
    include_staged: bool = True,
    include_unstaged: bool = True,
) -> DiffOnlyResult:
    """
    Lấy chỉ git diff - không bao gồm source code đầy đủ.

    Mục đích: Cho AI review các thay đổi gần đây mà không cần context toàn bộ project.

    Args:
        workspace_path: Path đến workspace
        num_commits: Số commits gần nhất cần include (0 = chỉ uncommitted changes)
        include_staged: Bao gồm staged changes
        include_unstaged: Bao gồm unstaged changes

    Returns:
        DiffOnlyResult với diff content và statistics
    """
    if not is_git_repo(workspace_path):
        return DiffOnlyResult(
            diff_content="",
            files_changed=0,
            insertions=0,
            deletions=0,
            commits_included=0,
            error="Not a git repository",
        )

    diff_parts: list[str] = []
    changed_files: list[str] = []  # Track changed file paths
    total_files = 0
    total_insertions = 0
    total_deletions = 0

    try:
        # 1. Uncommitted changes (staged + unstaged)
        if include_unstaged:
            # Unstaged changes (working tree vs index)
            result = subprocess.run(
                ["git", "diff", "--stat"],
                cwd=workspace_path,
                capture_output=True,
                text=True,
                timeout=30,
            )
            result_stdout = result.stdout or ""
            if result.returncode == 0 and result_stdout.strip():
                unstaged_diff = subprocess.run(
                    ["git", "diff"],
                    cwd=workspace_path,
                    capture_output=True,
                    text=True,
                    timeout=30,
                )
                unstaged_stdout = unstaged_diff.stdout or ""
                if unstaged_stdout.strip():
                    diff_parts.append("# Unstaged Changes (Working Tree)\n")
                    diff_parts.append(unstaged_stdout)
                    # Parse stats
                    stats = _parse_diff_stats(result_stdout)
                    total_files += stats[0]
                    total_insertions += stats[1]
                    total_deletions += stats[2]
                    # Collect changed files
                    changed_files.extend(_extract_changed_files(result_stdout))

        if include_staged:
            # Staged changes (index vs HEAD)
            result = subprocess.run(
                ["git", "diff", "--cached", "--stat"],
                cwd=workspace_path,
                capture_output=True,
                text=True,
                timeout=30,
            )
            result_stdout = result.stdout or ""
            if result.returncode == 0 and result_stdout.strip():
                staged_diff = subprocess.run(
                    ["git", "diff", "--cached"],
                    cwd=workspace_path,
                    capture_output=True,
                    text=True,
                    timeout=30,
                )
                staged_stdout = staged_diff.stdout or ""
                if staged_stdout.strip():
                    diff_parts.append("\n# Staged Changes (Ready to Commit)\n")
                    diff_parts.append(staged_stdout)
                    stats = _parse_diff_stats(result_stdout)
                    total_files += stats[0]
                    total_insertions += stats[1]
                    total_deletions += stats[2]
                    # Collect changed files
                    changed_files.extend(_extract_changed_files(result_stdout))

        # 2. Recent commits diff
        commits_included = 0
        if num_commits > 0:
            # Get diff of last N commits
            result = subprocess.run(
                ["git", "log", f"-{num_commits}", "--oneline"],
                cwd=workspace_path,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=30,
            )
            result_stdout = result.stdout or ""
            if result.returncode == 0 and result_stdout.strip():
                commit_lines = result_stdout.strip().split("\n")
                commits_included = len(commit_lines)

                # Get combined diff
                diff_result = subprocess.run(
                    ["git", "diff", "--no-color", f"HEAD~{num_commits}..HEAD"],
                    cwd=workspace_path,
                    capture_output=True,
                    text=True,
                    encoding="utf-8",
                    errors="replace",
                    timeout=60,
                )
                diff_stdout = diff_result.stdout or ""

                # Fallback cho repo nông/ít history (ví dụ clone depth=1, initial commit)
                # nơi HEAD~N không resolve được trên một số máy Windows.
                if diff_result.returncode != 0:
                    diff_result = subprocess.run(
                        ["git", "diff", "--no-color", "--root", "HEAD"],
                        cwd=workspace_path,
                        capture_output=True,
                        text=True,
                        encoding="utf-8",
                        errors="replace",
                        timeout=60,
                    )
                    diff_stdout = diff_result.stdout or ""

                if diff_result.returncode == 0 and diff_stdout.strip():
                    diff_parts.append(
                        f"\n# Recent Commits ({commits_included} commits)\n"
                    )
                    diff_parts.append("# Commits:\n")
                    for line in commit_lines:
                        diff_parts.append(f"#   {line}\n")
                    diff_parts.append("\n")
                    diff_parts.append(diff_result.stdout)

                    # Get stats
                    stat_result = subprocess.run(
                        ["git", "diff", "--stat", f"HEAD~{num_commits}..HEAD"],
                        cwd=workspace_path,
                        capture_output=True,
                        text=True,
                        encoding="utf-8",
                        errors="replace",
                        timeout=30,
                    )
                    if stat_result.returncode != 0:
                        stat_result = subprocess.run(
                            ["git", "diff", "--stat", "--root", "HEAD"],
                            cwd=workspace_path,
                            capture_output=True,
                            text=True,
                            encoding="utf-8",
                            errors="replace",
                            timeout=30,
                        )
                    if stat_result.returncode == 0:
                        stats = _parse_diff_stats(stat_result.stdout or "")
                        total_files += stats[0]
                        total_insertions += stats[1]
                        total_deletions += stats[2]
                        # Collect changed files from commits
                        changed_files.extend(_extract_changed_files(stat_result.stdout))

        diff_content = "".join(diff_parts)

        # Deduplicate changed files while preserving order
        seen: set[str] = set()
        unique_files: list[str] = []
        for f in changed_files:
            if f not in seen:
                seen.add(f)
                unique_files.append(f)

        return DiffOnlyResult(
            diff_content=diff_content,
            files_changed=total_files,
            insertions=total_insertions,
            deletions=total_deletions,
            commits_included=commits_included,
            changed_files=unique_files,
            error=None,
        )

    except subprocess.TimeoutExpired:
        return DiffOnlyResult(
            diff_content="",
            files_changed=0,
            insertions=0,
            deletions=0,
            commits_included=0,
            error="Git command timed out",
        )
    except Exception as e:
        return DiffOnlyResult(
            diff_content="",
            files_changed=0,
            insertions=0,
            deletions=0,
            commits_included=0,
            error=str(e),
        )


def _normalize_diff_path(path: str) -> str:
    """Normalize path separators de compare path on all platforms."""
    return path.replace("\\", "/").strip()


def _parse_diff_git_header_line(line: str) -> Optional[tuple[str, str]]:
    """Parse a `diff --git` header line va tra ve (old_path, new_path)."""
    match = _DIFF_GIT_HEADER_RE.match(line.strip())
    if not match:
        return None

    old_path = match.group(1) or match.group(2) or ""
    new_path = match.group(3) or match.group(4) or ""
    return (_normalize_diff_path(old_path), _normalize_diff_path(new_path))


def extract_changed_files_from_diff(diff_content: str) -> list[str]:
    """
    Extract changed file paths from unified diff content.

    Args:
        diff_content: Raw unified diff string

    Returns:
        Ordered unique list of changed file paths
    """
    seen: set[str] = set()
    files: list[str] = []

    for line in diff_content.splitlines():
        if not line.startswith("diff --git "):
            continue

        parsed = _parse_diff_git_header_line(line)
        if not parsed:
            continue

        old_path, new_path = parsed
        path = new_path or old_path
        if path and path not in seen:
            seen.add(path)
            files.append(path)

    return files


def filter_diff_by_files(diff_content: str, selected_files: list[str]) -> str:
    """
    Filter unified diff content and keep only selected file blocks.

    Args:
        diff_content: Raw unified diff string
        selected_files: List of selected relative file paths

    Returns:
        Filtered diff string containing only selected files
    """
    if not selected_files:
        return ""

    selected = {
        _normalize_diff_path(path)
        for path in selected_files
        if _normalize_diff_path(path)
    }
    if not selected:
        return ""

    kept_blocks: list[str] = []
    current_block: list[str] = []
    current_path: Optional[str] = None

    for line in diff_content.splitlines(keepends=True):
        if line.startswith("diff --git "):
            if current_block and current_path and current_path in selected:
                kept_blocks.append("".join(current_block))

            current_block = [line]
            parsed = _parse_diff_git_header_line(line)
            if parsed:
                old_path, new_path = parsed
                current_path = new_path or old_path
            else:
                current_path = None
            continue

        if current_block:
            current_block.append(line)

    if current_block and current_path and current_path in selected:
        kept_blocks.append("".join(current_block))

    return "".join(kept_blocks)


def _parse_diff_stats(stat_output: str) -> tuple[int, int, int]:
    """
    Parse git diff --stat output để lấy files changed, insertions, deletions.

    Returns:
        (files_changed, insertions, deletions)
    """
    # Last line format: "X files changed, Y insertions(+), Z deletions(-)"
    lines = stat_output.strip().split("\n")
    if not lines:
        return (0, 0, 0)

    last_line = lines[-1]

    files = 0
    insertions = 0
    deletions = 0

    # Parse files changed
    files_match = re.search(r"(\d+) files? changed", last_line)
    if files_match:
        files = int(files_match.group(1))

    # Parse insertions
    ins_match = re.search(r"(\d+) insertions?\(\+\)", last_line)
    if ins_match:
        insertions = int(ins_match.group(1))

    # Parse deletions
    del_match = re.search(r"(\d+) deletions?\(-\)", last_line)
    if del_match:
        deletions = int(del_match.group(1))

    return (files, insertions, deletions)


def _extract_changed_files(stat_output: str) -> list[str]:
    """
    Extract danh sách file paths từ git diff --stat output.

    Format của mỗi dòng: " path/to/file.py | N +++ --"

    Args:
        stat_output: Output từ git diff --stat

    Returns:
        List các file paths đã thay đổi
    """
    files: list[str] = []
    lines = stat_output.strip().split("\n")

    for line in lines:
        # Skip summary line (cuối cùng chứa "files changed")
        if "changed" in line and ("insertion" in line or "deletion" in line):
            continue

        # Format: " path/to/file | stats"
        if "|" in line:
            file_part = line.split("|")[0].strip()
            if file_part:
                # Handle renamed files: "old_name => new_name"
                if "=>" in file_part:
                    # Lấy new name
                    parts = file_part.split("=>")
                    if len(parts) == 2:
                        file_part = parts[1].strip()
                        # Handle path prefix: "{dir/}old => new"
                        if "{" in parts[0]:
                            prefix = parts[0].split("{")[0]
                            file_part = prefix + file_part.rstrip("}")
                files.append(file_part)

    return files


def build_diff_only_prompt(
    diff_result: DiffOnlyResult,
    instructions: str,
    include_changed_content: bool,
    include_tree_structure: bool,
    workspace_root: Optional[Path] = None,
    use_relative_paths: bool = False,
    include_related_files: bool = False,
    related_depth: int = 1,
    related_max_files: int = 20,
    output_format: str | _OutputFormatLike = "xml",
) -> str:
    """
    Build prompt from diff result for Copy Diff Only feature.

    Args:
        diff_result: DiffOnlyResult from get_diff_only()
        instructions: User instructions text
        include_changed_content: Include full content of changed files
        include_tree_structure: Include changed file tree structure
        workspace_root: Workspace root de resolve path va convert relative (optional)
        use_relative_paths: True = xuat path tuong doi workspace (tranh PII)
        include_related_files: Include imported related files content
        related_depth: Import depth for related files
        related_max_files: Max related files to include
        output_format: "xml" hoặc "plain" / "text" / "markdown" / "json"

    Returns:
        Formatted prompt string
    """
    if isinstance(output_format, str):
        normalized_output_format = output_format
    else:
        normalized_output_format = str(output_format.value)

    is_xml = normalized_output_format.lower() == "xml"
    is_json = normalized_output_format.lower() == "json"
    is_markdown = normalized_output_format.lower() == "markdown"
    is_plain = normalized_output_format.lower() in ("plain", "text")

    if is_xml:
        parts = [_generate_diff_summary_xml(), ""]
        parts.extend(
            [
                "<diff_context>",
                f"Files changed: {diff_result.files_changed}",
                f"Lines: +{diff_result.insertions} / -{diff_result.deletions}",
            ]
        )
        if diff_result.commits_included > 0:
            parts.append(f"Commits included: {diff_result.commits_included}")
        parts.extend(["</diff_context>", ""])

        if include_tree_structure and diff_result.changed_files:
            tree_str = _build_tree_xml_from_paths(diff_result.changed_files[:50])
            parts.extend(["<structure>", tree_str, "</structure>", ""])

        parts.extend(["<git_diff>", diff_result.diff_content, "</git_diff>"])

        if include_changed_content and diff_result.changed_files:
            parts.extend(["", "<changed_files_content>"])
            for file_path in diff_result.changed_files[:20]:
                full_path = (
                    (workspace_root / file_path) if workspace_root else Path(file_path)
                )
                if full_path.exists() and full_path.is_file():
                    try:
                        content = full_path.read_text(
                            encoding="utf-8", errors="replace"
                        )
                        if len(content) <= 50000:
                            from shared.utils.language_utils import (
                                get_language_from_path,
                            )

                            lang = get_language_from_path(str(full_path))
                            path_display = path_for_display(
                                full_path, workspace_root, use_relative_paths
                            )
                            parts.extend(
                                [
                                    f'<file path="{path_display}">',
                                    f"```{lang}",
                                    content,
                                    "```",
                                    "</file>",
                                ]
                            )
                    except Exception:
                        pass
            parts.append("</changed_files_content>")

        if include_related_files and workspace_root and diff_result.changed_files:
            try:
                from shared.utils.import_parser import get_related_files

                related_files = get_related_files(
                    changed_files=diff_result.changed_files,
                    workspace_root=workspace_root,
                    depth=max(1, related_depth),
                    max_files=max(1, related_max_files),
                )

                if related_files:
                    parts.extend(["", "<related_files_content>"])
                    for file_path in related_files:
                        full_path = workspace_root / file_path
                        if full_path.exists() and full_path.is_file():
                            try:
                                content = full_path.read_text(
                                    encoding="utf-8", errors="replace"
                                )
                                if len(content) <= 50000:
                                    from shared.utils.language_utils import (
                                        get_language_from_path,
                                    )

                                    lang = get_language_from_path(str(full_path))
                                    path_display = path_for_display(
                                        full_path, workspace_root, use_relative_paths
                                    )
                                    parts.extend(
                                        [
                                            f'<file path="{path_display}">',
                                            f"```{lang}",
                                            content,
                                            "```",
                                            "</file>",
                                        ]
                                    )
                            except Exception:
                                pass
                    parts.append("</related_files_content>")
            except Exception:
                pass

        if instructions and instructions.strip():
            parts.extend(
                [
                    "",
                    "<user_instructions>",
                    instructions.strip(),
                    "</user_instructions>",
                ]
            )

    elif is_json:
        # Simple JSON assembly cho diff
        import json

        data: dict[str, Any] = {
            "summary": DIFF_SUMMARY_HEADER,
            "purpose": DIFF_SUMMARY_PURPOSE,
            "context": {
                "files_changed": diff_result.files_changed,
                "insertions": diff_result.insertions,
                "deletions": diff_result.deletions,
                "commits_included": diff_result.commits_included,
            },
            "diff": diff_result.diff_content,
        }
        if include_tree_structure and diff_result.changed_files:
            data["structure"] = _build_tree_xml_from_paths(
                diff_result.changed_files[:50]
            )

        if include_changed_content and diff_result.changed_files:
            contents: list[dict[str, str]] = []
            for file_path in diff_result.changed_files[:20]:
                full_path = (
                    (workspace_root / file_path) if workspace_root else Path(file_path)
                )
                if full_path.exists() and full_path.is_file():
                    try:
                        content = full_path.read_text(
                            encoding="utf-8", errors="replace"
                        )
                        if len(content) <= 50000:
                            path_display = path_for_display(
                                full_path, workspace_root, use_relative_paths
                            )
                            contents.append({"path": path_display, "content": content})
                    except Exception:
                        pass
            data["changed_files_content"] = contents

        if instructions and instructions.strip():
            data["user_instructions"] = instructions.strip()

        return json.dumps(data, indent=2, ensure_ascii=False)

    elif is_markdown:
        # Markdown format
        parts = ["# FILE SUMMARY", _generate_diff_summary_plain(), ""]
        parts.extend(
            [
                "## DIFF CONTEXT",
                f"- Files changed: {diff_result.files_changed}",
                f"- Lines: +{diff_result.insertions} / -{diff_result.deletions}",
            ]
        )
        if diff_result.commits_included > 0:
            parts.append(f"- Commits included: {diff_result.commits_included}")
        parts.append("")

        if include_tree_structure and diff_result.changed_files:
            tree_str = _build_tree_from_paths(diff_result.changed_files[:50])
            parts.extend(["## STRUCTURE", "```", tree_str, "```", ""])

        parts.extend(["## GIT DIFF", "```diff", diff_result.diff_content, "```"])

        if include_changed_content and diff_result.changed_files:
            parts.extend(["", "## CHANGED FILES CONTENT"])
            for file_path in diff_result.changed_files[:20]:
                full_path = (
                    (workspace_root / file_path) if workspace_root else Path(file_path)
                )
                if full_path.exists() and full_path.is_file():
                    try:
                        content = full_path.read_text(
                            encoding="utf-8", errors="replace"
                        )
                        if len(content) <= 50000:
                            from shared.utils.language_utils import (
                                get_language_from_path,
                            )

                            lang = get_language_from_path(str(full_path))
                            path_display = path_for_display(
                                full_path, workspace_root, use_relative_paths
                            )
                            parts.extend(
                                [
                                    "",
                                    f"### File: {path_display}",
                                    f"```{lang}",
                                    content,
                                    "```",
                                ]
                            )
                    except Exception:
                        pass

        if instructions and instructions.strip():
            parts.extend(
                [
                    "",
                    "## USER INSTRUCTIONS",
                    "> " + instructions.strip().replace("\n", "\n> "),
                ]
            )

    elif (
        is_plain or True
    ):  # Sử dụng is_plain để pass lint, True để đảm bảo fallback luôn chạy
        # Plain text (fallback cho ca markdown de don gian)
        parts = [_generate_diff_summary_plain(), ""]
        parts.extend(
            [
                f"{'-' * 48}",
                "DIFF CONTEXT",
                f"{'-' * 48}",
                f"Files changed: {diff_result.files_changed}",
                f"Lines: +{diff_result.insertions} / -{diff_result.deletions}",
            ]
        )
        if diff_result.commits_included > 0:
            parts.append(f"Commits included: {diff_result.commits_included}")
        parts.append("")

        if include_tree_structure and diff_result.changed_files:
            tree_str = _build_tree_from_paths(diff_result.changed_files[:50])
            parts.extend([f"{'-' * 48}", "STRUCTURE", f"{'-' * 48}", tree_str, ""])

        parts.extend(
            [f"{'-' * 48}", "GIT DIFF", f"{'-' * 48}", diff_result.diff_content]
        )

        if include_changed_content and diff_result.changed_files:
            parts.extend(["", f"{'-' * 48}", "CHANGED FILES CONTENT", f"{'-' * 48}"])
            for file_path in diff_result.changed_files[:20]:
                full_path = (
                    (workspace_root / file_path) if workspace_root else Path(file_path)
                )
                if full_path.exists() and full_path.is_file():
                    try:
                        content = full_path.read_text(
                            encoding="utf-8", errors="replace"
                        )
                        if len(content) <= 50000:
                            path_display = path_for_display(
                                full_path, workspace_root, use_relative_paths
                            )
                            parts.extend(
                                [
                                    "",
                                    f"File: {path_display}",
                                    f"{'=' * len(path_display)}",
                                    content,
                                ]
                            )
                    except Exception:
                        pass

        if instructions and instructions.strip():
            parts.extend(
                [
                    "",
                    f"{'-' * 48}",
                    "USER INSTRUCTIONS",
                    f"{'-' * 48}",
                    instructions.strip(),
                ]
            )

    return "\n".join(parts)


def _build_tree_from_paths(file_paths: list[str]) -> str:
    """Build tree hierarchy string from a list of file paths."""
    tree_dict: dict[str, Any] = {}
    for file_path in file_paths:
        path_parts = file_path.replace("\\", "/").split("/")
        current: dict[str, Any] = tree_dict
        for i, part in enumerate(path_parts):
            if i == len(path_parts) - 1:
                current[part] = None  # file
            else:
                if part not in current:
                    current[part] = {}
                current = current[part]

    lines: list[str] = []
    _render_tree_dict(tree_dict, lines, prefix="")
    return "\n".join(lines)


def _build_tree_xml_from_paths(file_paths: list[str]) -> str:
    """Xây dựng cấu trúc cây XML từ danh sách file paths."""
    tree_dict: dict[str, Any] = {}
    for file_path in file_paths:
        path_parts = file_path.replace("\\", "/").split("/")
        current: dict[str, Any] = tree_dict
        for i, part in enumerate(path_parts):
            if i == len(path_parts) - 1:
                current[part] = None  # file
            else:
                if part not in current:
                    current[part] = {}
                current = current[part]

    lines: list[str] = []
    _render_tree_xml_dict(tree_dict, lines, indent_level=1)
    return "\n".join(lines)


def _render_tree_dict(
    tree_dict: dict[str, Any], lines: list[str], prefix: str = ""
) -> None:
    """Render tree dict dùng ├──/└──/│ giống _build_tree_string trong prompt_generator."""
    # Sắp xếp: folders trước, files sau (giống scan_directory)
    items: list[tuple[str, Any]] = sorted(
        tree_dict.items(), key=lambda x: (x[1] is None, x[0])
    )
    for i, (name, children) in enumerate(items):
        is_last = i == len(items) - 1
        connector = "└── " if is_last else "├── "
        if children is None:
            # File — thêm marker [modified]
            lines.append(f"{prefix}{connector}{name} [modified]")
        else:
            # Folder
            lines.append(f"{prefix}{connector}{name}/")
            # Prefix cho children: "    " nếu là item cuối, "│   " nếu còn item khác
            new_prefix = prefix + ("    " if is_last else "│   ")
            _render_tree_dict(children, lines, new_prefix)


def _render_tree_xml_dict(
    tree_dict: dict[str, Any], lines: list[str], indent_level: int = 1
) -> None:
    """Render tree dict thành XML tags."""
    indent = "  " * indent_level
    # Sắp xếp: folders trước, files sau
    items: list[tuple[str, Any]] = sorted(
        tree_dict.items(), key=lambda x: (x[1] is None, x[0])
    )

    for name, children in items:
        if children is None:
            # File tag
            lines.append(f'{indent}<file name="{name}" status="modified" />')
        else:
            # Folder tag
            lines.append(f'{indent}<folder name="{name}">')
            _render_tree_xml_dict(children, lines, indent_level + 1)
            lines.append(f"{indent}</folder>")
